In [1]:
import requests
import pandas as pd
import os
import re

In [2]:
df_donosti = pd.read_csv("donosti_csv\datos_donosti.csv", sep =",")
df_donosti

,fecha,tm_mes,tm_max,tm_min,ta_max,ta_min,ti_max,ts_min,p_mes,np_300,nt_30,inso
0,1970-1,9.5,12.1,6.8,18.0(19),-1.4(07),5.0,13.0,196.7,2.0,0.0,2.4
1,1970-2,7.7,9.9,5.5,14.0(04),-2.0(28),3.0,11.0,165.8,0.0,0.0,2.3
2,1970-3,7.2,10.0,4.3,20.6(21),-1.2(02),2.1,9.5,101.0,0.0,0.0,2.6
3,1970-4,9.5,12.5,6.5,26.5(16),1.2(03),6.9,10.9,174.3,1.0,0.0,3.9
4,1970-5,14.0,17.4,10.4,30.6(24),5.0(08),9.4,15.0,89.4,1.0,1.0,6.1
...,...,...,...,...,...,...,...,...,...,...,...,...
684,2022-9,18.6,22.1,15.1,33.9(11),10.3(25),14.0,22.5,147.6,2.0,4.0,6.4
685,2022-10,19.6,22.9,16.3,28.0(19),11.8(01),17.7,24.3,40.6,0.0,0.0,4.1
686,2022-11,13.4,16.5,10.2,22.0(13),6.4(19),9.5,17.5,317.3,4.0,0.0,3.6
687,2022-12,11.9,14.7,9.0,20.0(31),2.0(10),7.4,15.7,82.4,0.0,0.0,2.9
688,2022-13,15.1,18.3,11.9,39.7(18/jun),0.4(23/ene),4.0,24.3,1338.2,9.0,15.0,5.3

In [3]:
#Separamos la columna "fecha" con año-mes en dos
df_donosti[['año', 'mes']] = df_donosti['fecha'].str.split('-', expand=True)
# Eliminamos la columna "fecha"
df_donosti2 = df_donosti.drop(columns=["fecha"], axis=1)
# Ponemos las nuevas columnas año, mes las primeras
column_order = ['año', 'mes'] + df_donosti2.columns.tolist()[:-2]
df_donosti3 = df_donosti2.reindex(columns=column_order)
df_donosti3
df_donosti3['ta_max'] = df_donosti3['ta_max'].str.replace(r'\(.*\)', '', regex=True)
df_donosti3['ta_min'] = df_donosti3['ta_min'].str.replace(r'\(.*\)', '', regex=True)
df_donosti3
# Así se pasan las filas de los datos anuales a otro dataframe
df_donosti_anual = pd.DataFrame(df_donosti3.iloc[12::13])
df_donosti_anual
# Y eliminamos esas filas del dataframe original
df_donosti_final = df_donosti3.drop(range(12,663,13), axis=0)
df_donosti_final
#Generamos csv y xlsx para guardar los archivos y que no se pierda el trabajo
df_donosti_anual.to_csv('donosti_anual.csv', index=False)
df_donosti_final.to_csv('donosti_anual.csv', index=False)
df_donosti_anual.to_excel('donosti_anual.xlsx', index=False)
df_donosti_anual.to_excel('donosti_anual.xlsx', index=False)

#Falta detectar valores nulos y hacer esto para los dataframes de vitoria y donosti

In [4]:
df_donosti_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 638 entries, 0 to 688
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   año     638 non-null    object
 1   mes     638 non-null    object
 2   tm_mes  638 non-null    float64
 3   tm_max  638 non-null    float64
 4   tm_min  638 non-null    float64
 5   ta_max  638 non-null    object
 6   ta_min  638 non-null    object
 7   ti_max  638 non-null    float64
 8   ts_min  638 non-null    float64
 9   p_mes   638 non-null    float64
 10  np_300  638 non-null    float64
 11  nt_30   638 non-null    float64
 12  inso    632 non-null    float64
dtypes: float64(9), object(4)
memory usage: 69.8+ KB

In [5]:
df_donosti_final['inso'] = df_donosti_final['inso'].fillna(0)
df_donosti_final_sinull = df_donosti_final
df_donosti_final_sinull.reset_index(drop=True, inplace=True)
df_donosti_final_sinull.to_csv('donosti_final_sinull.csv', index=False)
df_donosti_final_sinull.to_excel('donosti_final_sinull.xlsx', index=False)
df_donosti_final_sinull

,año,mes,tm_mes,tm_max,tm_min,ta_max,ta_min,ti_max,ts_min,p_mes,np_300,nt_30,inso
0,1970,1,9.5,12.1,6.8,18.0,-1.4,5.0,13.0,196.7,2.0,0.0,2.4
1,1970,2,7.7,9.9,5.5,14.0,-2.0,3.0,11.0,165.8,0.0,0.0,2.3
2,1970,3,7.2,10.0,4.3,20.6,-1.2,2.1,9.5,101.0,0.0,0.0,2.6
3,1970,4,9.5,12.5,6.5,26.5,1.2,6.9,10.9,174.3,1.0,0.0,3.9
4,1970,5,14.0,17.4,10.4,30.6,5.0,9.4,15.0,89.4,1.0,1.0,6.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
633,2022,9,18.6,22.1,15.1,33.9,10.3,14.0,22.5,147.6,2.0,4.0,6.4
634,2022,10,19.6,22.9,16.3,28.0,11.8,17.7,24.3,40.6,0.0,0.0,4.1
635,2022,11,13.4,16.5,10.2,22.0,6.4,9.5,17.5,317.3,4.0,0.0,3.6
636,2022,12,11.9,14.7,9.0,20.0,2.0,7.4,15.7,82.4,0.0,0.0,2.9
637,2022,13,15.1,18.3,11.9,39.7,0.4,4.0,24.3,1338.2,9.0,15.0,5.3

In [6]:
df_donosti_final_sinull.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 638 entries, 0 to 637
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   año     638 non-null    object
 1   mes     638 non-null    object
 2   tm_mes  638 non-null    float64
 3   tm_max  638 non-null    float64
 4   tm_min  638 non-null    float64
 5   ta_max  638 non-null    object
 6   ta_min  638 non-null    object
 7   ti_max  638 non-null    float64
 8   ts_min  638 non-null    float64
 9   p_mes   638 non-null    float64
 10  np_300  638 non-null    float64
 11  nt_30   638 non-null    float64
 12  inso    638 non-null    float64
dtypes: float64(9), object(4)
memory usage: 64.9+ KB

In [7]:
df_donosti_anual['inso'] = df_donosti_anual['inso'].fillna(0)
df_donosti_anual_sinull = df_donosti_anual
df_donosti_anual_sinull2=df_donosti_anual_sinull.drop(["mes"], axis=1)
df_donosti_anual_sinull2.reset_index(drop=True, inplace=True)
df_donosti_anual_sinull2.to_csv('donosti_anual_sinull2.csv', index=False)
df_donosti_anual_sinull2.to_excel('donosti_anual_sinull2.xlsx', index=False)
df_donosti_anual_sinull2

,año,tm_mes,tm_max,tm_min,ta_max,ta_min,ti_max,ts_min,p_mes,np_300,nt_30,inso
0,1970,13.1,16.1,10.1,34.6,-2.0,1.8,21.6,1441.5,9.0,5.0,4.4
1,1971,12.9,16.0,9.8,32.2,-5.5,1.0,23.0,1594.0,4.0,4.0,4.4
2,1972,12.3,15.4,9.2,32.2,-1.3,5.0,19.0,1366.8,6.0,2.0,4.4
3,1973,12.8,16.0,9.6,33.0,-6.7,2.0,22.0,1532.1,8.0,5.0,4.5
4,1974,12.5,15.7,9.3,36.4,0.0,5.3,21.8,1840.2,8.0,4.0,4.0
5,1975,12.7,15.7,9.8,38.0,-1.0,3.0,20.6,1363.6,7.0,5.0,4.3
6,1976,12.9,16.0,9.8,33.4,-2.2,1.6,21.2,1566.9,9.0,2.0,4.8
7,1977,12.8,15.8,9.7,31.0,-1.8,2.2,18.4,1678.3,11.0,1.0,4.1
8,1978,12.5,15.4,9.5,30.6,-1.0,2.6,20.4,1629.8,12.0,1.0,4.1
9,1979,12.7,15.6,9.7,30.0,-2.8,2.8,19.6,2206.3,17.0,1.0,0.0
10,1980,12.4,15.6,9.2,33.0,-4.6,-0.8,19.6,1718.7,12.0,4.0,3.8
11,1981,13.0,16.2,9.8,35.0,-1.8,1.2,21.0,1802.5,7.0,5.0,4.3
12,1982,13.5,16.4,10.5,37.6,0.4,5.6,21.8,1652.3,10.0,6.0,0.0
13,1983,13.6,16.7,10.6,31.4,-5.0,-0.2,25.2,1365.0,8.0,8.0,3.5
14,1984,12.5,15.4,9.6,33.2,-1.6,3.6,19.4,1764.8,11.0,6.0,3.8
15,1985,12.7,15.9,9.6,34.0,-10.0,-3.5,19.6,1352.8,7.0,6.0,3.9
16,1986,12.5,15.4,9.6,34.0,-5.8,0.0,20.0,1732.6,9.0,4.0,4.4
17,1987,13.3,16.3,10.3,35.0,-3.8,0.0,23.0,1409.6,8.0,8.0,4.6
18,1988,13.4,16.4,10.5,34.0,-3.4,2.6,23.6,1350.8,3.0,2.0,4.9
19,1989,14.6,17.6,11.6,35.4,-1.4,2.8,20.2,1088.7,6.0,3.0,6.1
20,1990,14.0,17.0,10.9,32.6,-1.4,1.8,21.6,1594.0,11.0,4.0,5.5
21,1991,12.9,15.7,10.0,35.8,-1.4,3.4,20.8,1358.1,7.0,4.0,4.8
22,1992,13.0,15.9,10.1,33.4,-3.0,3.0,21.6,1668.7,11.0,6.0,4.3
23,1993,13.2,16.0,10.3,34.2,-2.4,2.4,23.4,1364.1,10.0,4.0,4.9
24,1994,13.8,16.5,10.9,33.6,-2.6,3.2,20.2,1748.5,14.0,3.0,4.6
25,1995,14.0,16.9,11.0,36.2,-2.0,1.2,20.6,1311.6,6.0,3.0,5.4
26,1996,13.3,16.0,10.5,35.0,-3.2,2.0,20.4,1602.7,10.0,4.0,5.3
27,1997,14.6,17.6,11.6,30.6,-0.4,2.0,21.4,1733.5,14.0,2.0,5.4
28,1998,13.7,16.7,10.7,35.2,-1.8,4.6,21.2,1537.3,8.0,7.0,5.2
29,1999,13.6,16.5,10.7,32.0,-2.2,1.8,20.6,1428.3,6.0,3.0,4.7
30,2000,13.8,16.8,10.8,33.4,-1.6,3.0,20.4,1582.5,5.0,8.0,4.9
31,2001,13.7,16.7,10.8,31.2,-5.6,1.5,22.0,1058.2,2.0,5.0,5.1
32,2002,14.0,16.8,11.1,31.2,1.8,5.9,20.8,1676.9,13.0,2.0,4.8
33,2003,14.5,17.5,11.5,38.6,-4.0,1.7,23.0,1348.9,7.0,12.0,5.1
34,2004,13.6,16.4,10.7,34.2,-0.8,2.8,23.2,1431.9,6.0,7.0,5.1
35,2005,13.4,16.4,10.4,35.0,-4.7,0.6,20.4,1363.2,7.0,10.0,5.6
36,2006,14.4,17.4,11.4,36.0,-1.6,2.4,22.0,1248.9,11.0,7.0,5.2
37,2007,13.3,16.2,10.5,34.6,-3.2,0.6,23.9,1536.1,7.0,5.0,4.8
38,2008,13.4,16.4,10.4,32.8,0.4,4.7,19.1,1909.5,14.0,4.0,5.0
39,2009,13.5,16.5,10.6,35.6,-2.6,0.6,22.6,1700.9,10.0,5.0,5.0
40,2010,13.0,15.9,10.0,33.6,-3.7,0.5,21.4,1477.8,8.0,4.0,5.0
41,2011,14.5,17.4,11.6,37.2,-1.6,2.0,20.8,1400.9,10.0,7.0,5.3
42,2012,13.5,16.7,10.3,36.7,-5.3,0.2,20.6,1602.8,9.0,12.0,5.3
43,2013,13.3,16.2,10.4,36.4,-3.0,2.3,21.8,2145.1,9.0,3.0,4.9
44,2014,14.4,17.4,11.4,33.4,-0.8,3.0,19.0,1725.3,8.0,2.0,5.1
45,2015,14.1,17.2,11.0,35.4,-2.0,0.9,19.8,1437.1,9.0,11.0,5.0
46,2016,14.1,17.1,11.0,36.7,0.3,6.0,22.2,1586.1,9.0,9.0,5.2
47,2017,14.0,17.2,10.7,36.2,-2.9,-0.4,22.5,1568.5,6.0,11.0,5.2
48,2018,14.1,16.9,11.2,32.0,-5.1,0.1,20.5,1757.6,14.0,2.0,4.8
49,2019,14.1,17.3,10.9,39.0,0.5,5.0,20.6,1900.1,12.0,7.0,5.4
50,2020,14.8,17.9,11.6,39.0,0.0,4.5,22.0,1780.2,14.0,9.0,5.2
51,2021,13.8,16.7,10.8,32.5,0.0,2.5,21.5,1676.6,14.0,3.0,4.9
52,2022,15.1,18.3,11.9,39.7,0.4,4.0,24.3,1338.2,9.0,15.0,5.3

In [8]:
df_donosti_anual_sinull2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   año     53 non-null     object
 1   tm_mes  53 non-null     float64
 2   tm_max  53 non-null     float64
 3   tm_min  53 non-null     float64
 4   ta_max  53 non-null     object
 5   ta_min  53 non-null     object
 6   ti_max  53 non-null     float64
 7   ts_min  53 non-null     float64
 8   p_mes   53 non-null     float64
 9   np_300  53 non-null     float64
 10  nt_30   53 non-null     float64
 11  inso    53 non-null     float64
dtypes: float64(9), object(3)
memory usage: 5.1+ KB